name: myhub

networks:
  myhub-net:
    name: myhub-net

services:
  myhub:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myhub
    hostname: myhub
    restart: unless-stopped
    networks:
      myhub-net:
    ports:
      - 80:80